<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Application extends Model
{
    use HasFactory;

    protected $fillable =[
        'name',
        'gender',
        'dob',
        'nationality',
        'sc_state',
        'study_centre',
        'p_address',
        'p_city',
        'p_state',
        'p_zip',
        'p_telephone',
        'p_mobile',
        'p_email',
        'occupation',
        'o_address',
        'o_city',
        'o_state',
        'o_zip',
        'eq_exam_x',
        'eq_board_x',
        'eq_year_x',
        'eq_marks_x',
        'eq_subject_x',
        'eq_exam_xii',
        'eq_board_xii',
        'eq_year_xii',
        'eq_marks_xii',
        'eq_subject_xii',
        'eq_exam_grad',
        'eq_board_grad',
        'eq_year_grad',
        'eq_marks_grad',
        'eq_subject_grad',
        'eq_exam_pgrad',
        'eq_board_pgrad',
        'eq_year_pgrad',
        'eq_marks_pgrad',
        'eq_subject_pgrad',
        'eq_exam_oth1',
        'eq_board_oth1',
        'eq_year_oth1',
        'eq_marks_oth1',
        'eq_subject_oth1',
        'eq_exam_oth2',
        'eq_board_oth2',
        'eq_year_oth2',
        'eq_marks_oth2',
        'eq_subject_oth2',
        'eq_exam_oth3',
        'eq_board_oth3',
        'eq_year_oth3',
        'eq_marks_oth3',
        'eq_subject_oth3',
        'pq_degree',
        'pq_board',
        'pq_year',
        'pq_marks',
        'pq_subject',
        'pq_degree1',
        'pq_board1',
        'pq_year1'.
        'pq_marks1',
        'pq_subject1',
        'pq_degree2',
        'pq_board2',
        'pq_year2',
        'pq_marks2',
        'pq_subject2',
        'pq_degree3',
        'pq_board3',
        'pq_year3',
        'pq_marks3',
        'pq_subject3',
        'status',
    ];
}
